// In-memory data store for backend fallback mode when MongoDB is offline

export const mockUsers = [
  {
    _id: 'user-admin',
    name: 'Asif Hossain',
    email: 'admin@shopio.com',
    password: 'admin123',
    isAdmin: true,
    role: 'superadmin',
    permissions: ['orders', 'products', 'categories', 'brands', 'coupons', 'shipping', 'pages', 'offers', 'banners', 'chat', 'settings', 'users'],
  },
  {
    _id: 'user-client',
    name: 'John Doe',
    email: 'user@shopio.com',
    password: 'user123',
    isAdmin: false,
    role: 'customer',
    permissions: [],
  }
];

export const mockCoupons = [
  {
    _id: 'coupon-1',
    code: 'SUMMER20',
    discount: 20,
    expiryDate: new Date('2030-01-01'),
    isActive: true,
  }
];

export const mockProducts = [
  {
    _id: 'mock-1',
    name: 'BoAt Wave Pro Smart Watch',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=300&auto=format&fit=crop',
    brand: 'BoAt',
    category: 'Electronics',
    description: 'A stylish and powerful smart watch featuring fitness tracking, notifications, and premium design.',
    price: 49.99,
    countInStock: 25,
    discountPercent: 35,
    isFlashSale: true,
    flashSaleEnd: '2026-06-10T23:59:59Z',
    rating: 4.5,
    numReviews: 35,
    reviews: [],
  },
  {
    _id: 'mock-2',
    name: 'Sony WH-1000XM5 Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=300&auto=format&fit=crop',
    brand: 'Sony',
    category: 'Electronics',
    description: 'Industry-leading noise canceling headphones with dual noise sensor technology and custom audio settings.',
    price: 199.99,
    countInStock: 10,
    discountPercent: 20,
    isFlashSale: true,
    flashSaleEnd: '2026-06-12T23:59:59Z',
    rating: 5.0,
    numReviews: 68,
    reviews: [],
  },
  {
    _id: 'mock-3',
    name: 'Nike Air Max 270 Shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=300&auto=format&fit=crop',
    brand: 'Nike',
    category: 'Accessories',
    description: 'Comfortable running and casual shoes featuring a responsive heel unit and dynamic mesh material.',
    price: 89.99,
    countInStock: 15,
    discountPercent: 30,
    isFlashSale: true,
    flashSaleEnd: '2026-06-08T23:59:59Z',
    rating: 4.0,
    numReviews: 35,
    reviews: [],
  },
  {
    _id: 'mock-4',
    name: 'Chanel Coco Mademoiselle',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=300&auto=format&fit=crop',
    brand: 'Chanel',
    category: 'Beauty',
    description: 'An elegant oriental-fresh fragrance designed for modern, independent women.',
    price: 99.99,
    countInStock: 8,
    discountPercent: 25,
    isFlashSale: true,
    flashSaleEnd: '2026-06-15T23:59:59Z',
    rating: 4.8,
    numReviews: 52,
    reviews: [],
  },
  {
    _id: 'mock-5',
    name: 'Men Green Jacket',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=300&auto=format&fit=crop',
    brand: 'Generic',
    category: 'Fashion',
    description: 'A classic and versatile outdoor green jacket for men, offering warmth and style.',
    price: 59.99,
    countInStock: 12,
    discountPercent: 0,
    isFlashSale: false,
    rating: 4.5,
    numReviews: 45,
    reviews: [],
  },
  {
    _id: 'mock-6',
    name: 'Women Handbag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=300&auto=format&fit=crop',
    brand: 'Generic',
    category: 'Fashion',
    description: 'A spacious and highly fashionable leather handbag designed for daily wear.',
    price: 49.99,
    countInStock: 6,
    discountPercent: 0,
    isFlashSale: false,
    rating: 5.0,
    numReviews: 35,
    reviews: [],
  },
  {
    _id: 'mock-7',
    name: 'Puma Running Shoes',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=300&auto=format&fit=crop',
    brand: 'Puma',
    category: 'Sports',
    description: 'High-performance running shoes equipped with breathable mesh and responsive cushioning technology.',
    price: 69.99,
    countInStock: 18,
    discountPercent: 0,
    isFlashSale: false,
    rating: 4.2,
    numReviews: 55,
    reviews: [],
  },
  {
    _id: 'mock-8',
    name: 'Fossil Black Watch',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=300&auto=format&fit=crop',
    brand: 'Fossil',
    category: 'Accessories',
    description: 'A classic black leather strap watch featuring an elegant minimalist dial.',
    price: 89.99,
    countInStock: 5,
    discountPercent: 0,
    isFlashSale: false,
    rating: 4.7,
    numReviews: 30,
    reviews: [],
  },
];

export const mockOrders = [];

export let mockSettings = {
  otpGateway: 'Simulated',
  otpLength: 6,
  otpExpiry: 5,
  bkashMode: 'Sandbox',
  bkashEnabled: true,
  bkashMerchantNumber: '01700000000',
  nagadMode: 'Sandbox',
  nagadEnabled: true,
  nagadMerchantId: 'NAGAD12345',
  sslcommerzMode: 'Sandbox',
  sslcommerzEnabled: true,
  sslcommerzStoreId: 'shopio_ssl_mock',
  codEnabled: true,
  advancePaymentEnabled: false,
  advancePaymentThreshold: 1000,
  advancePaymentPercent: 50,
  facebookPixelId: '',
  ga4MeasurementId: '',
  footerEmail: 'support@shopio.com',
  footerPhone: '+880 1712-345678',
  footerAddress: 'Dhaka, Bangladesh',
  footerCopyright: '© 2026 Shopio BD. All rights reserved.',
  footerNewsletterTitle: 'Subscribe to our newsletter',
  footerNewsletterSubtitle: 'Get the latest updates on new products, flash sales, and exclusive coupons.',
  footerFacebook: '',
  footerTwitter: '',
  footerInstagram: '',
  footerYoutube: '',
  popupEnabled: false,
  popupTitle: 'Special Offer!',
  popupText: 'Get 20% off your first order. Use code: WELCOME20',
  popupImage: '',
  popupLink: '',
  popupDelay: 3,
  recentSaleEnabled: true,
  recentSaleInterval: 30,
  customHeaderCode: '',
  currency: 'BDT',
  currencySymbol: '৳',
  siteTitle: 'Shopio - MERN E-Commerce',
  faviconUrl: '',
  headerLogo: '',
  footerLogo: '',
};

export let mockShippingMethods = [
  {
    _id: 'shipping-standard',
    name: 'Standard Delivery',
    price: 5.99,
    estimatedDays: '5-7 business days',
    description: 'Standard delivery via national courier service.',
    isActive: true,
    createdAt: new Date(),
  },
  {
    _id: 'shipping-express',
    name: 'Express Delivery',
    price: 12.99,
    estimatedDays: '1-2 business days',
    description: 'Fast express delivery with priority handling.',
    isActive: true,
    createdAt: new Date(),
  },
  {
    _id: 'shipping-free',
    name: 'Free Shipping',
    price: 0,
    estimatedDays: '7-10 business days',
    description: 'Free shipping for budget-friendly delivery.',
    isActive: true,
    createdAt: new Date(),
  },
];

