'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    // Header top bar
    findStore: 'Find a Store',
    compare: 'Compare',
    compareTitle: 'Product Comparison',
    comparePriceDiff: 'You Save',
    regularPrice: 'Regular Price',
    discountPrice: 'Discount Price',
    emptyCompare: 'Your comparison list is empty!',
    addToCompare: 'Add to Compare',
    maxCompareLimit: 'You can compare up to 3 products',
    trackOrder: 'Track Order',
    helpline: 'Helpline',
    // Nav
    home: 'Home',
    shop: 'Shop',
    categories: 'Categories',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
    brands: 'Brands',
    dailyDeals: 'Daily Deals',
    pages: 'Pages',
    shopByCategories: 'Shop By Categories',
    products: 'Products',
    store: 'Store',
    // Auth
    login: 'Login',
    logout: 'Logout',
    // Cart
    addToCart: 'Add to Cart',
    add: 'Add',
    quickView: 'Quick View',
    buyNow: 'Buy Now',
    whatsappOrder: 'WhatsApp Order',
    callToOrder: 'Call to Order',
    viewFullDetails: 'View Full Details',
    featuredProducts: 'Featured Products',
    handpicked: 'Handpicked quality collections for you.',
    viewAll: 'View All',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    freeDelivery: 'Free Delivery',
    freeDeliveryNote: 'On orders over ৳100',
    returnPolicy: '30 Days Return',
    returnNote: 'Money back guarantee',
    secureCheckout: 'Secure Checkout',
    secureNote: '100% Secure payments',
    customerReviews: 'Customer Reviews',
    // Wishlist
    wishlist: 'Wishlist',
    yourWishlist: 'Your Wishlist',
    wishlistEmpty: 'Your wishlist is empty. Tap the heart icons on products to save them!',
    // Shop
    allProducts: 'All Products',
    showing: 'Showing',
    results: 'results',
    allCategories: 'All Categories',
    allBrands: 'All Brands',
    allRatings: 'All Ratings',
    above: '& above',
    filters: 'Filters',
    reset: 'Reset',
    price: 'Price',
    rating: 'Rating',
    brand: 'Brand',
    newest: 'Newest',
    oldest: 'Oldest',
    priceLowHigh: 'Price: Low → High',
    priceHighLow: 'Price: High → Low',
    loadMore: 'Load More Products',
    loading: 'Loading...',
    noProducts: 'No products found matching your filter criteria.',
    resetFilters: 'Reset Filters',
    // Checkout
    secureCheckoutTitle: 'Secure Checkout',
    encryptedCheckout: '100% encrypted checkout experience.',
    myCart: 'My Cart',
    shipping: 'Shipping',
    payment: 'Payment',
    success: 'Success',
    cartEmpty: 'Your cart is empty',
    cartEmptyNote: 'Looks like you haven\'t added anything to your cart yet. Explore our top collections to start shopping!',
    startShopping: 'Start Shopping',
    productDetails: 'Product details',
    items: 'Items',
    orderSummary: 'Order Summary',
    haveCoupon: 'Have a coupon code?',
    selectCode: 'Select code...',
    applied: 'Applied',
    apply: 'Apply',
    remove: 'Remove',
    coupon: 'coupon',
    subtotal: 'Subtotal',
    shippingCost: 'Shipping',
    couponDiscount: 'Coupon Discount',
    totalPrice: 'Total Price',
    checkout: 'Checkout',
    shippingAddress: 'Shipping Address',
    shippingAddressNote: 'Please enter your physical shipping address details.',
    fullName: 'Full Name',
    deliveryAddress: 'Delivery Address',
    city: 'City',
    postalCode: 'Postal Code',
    phoneVerification: 'Phone Verification (OTP Required)',
    sendOtp: 'Send OTP',
    sending: 'Sending...',
    verify: 'Verify',
    verifying: 'Verifying...',
    verified: 'Verified!',
    enterOtp: 'Enter 6-digit OTP code',
    otpWarning: '* Please verify your phone number using OTP.',
    shippingMethods: 'Shipping Delivery Methods',
    shippingMethodNote: 'Select your preferred courier delivery speed.',
    confirmationSummary: 'Confirmation Summary',
    itemsSubtotal: 'Items Subtotal',
    deliveryShipping: 'Delivery Shipping',
    grandTotal: 'Grand Total',
    backToCart: 'Back to Cart',
    nextPayment: 'Next: Payment',
    advancePaymentRequired: 'Advance Payment Required',
    paymentOptions: 'Payment Options',
    paymentOptionsNote: 'Select your preferred payment method from the secure list.',
    finalCheckout: 'Final Checkout',
    shippingDelivery: 'Shipping Delivery',
    discountApplied: 'Discount Applied',
    totalPayable: 'Total Payable',
    back: 'Back',
    placingOrder: 'Placing Order...',
    confirmOrder: 'Confirm Order',
    thankYou: 'Thank you for your order!',
    orderPlaced: 'has been successfully placed.',
    orderStatus: 'Order Status:',
    pendingConfirmation: 'Pending Confirmation',
    paymentSelection: 'Payment Selection:',
    deliveryMethod: 'Delivery Method:',
    totalBill: 'Total Bill:',
    continueShopping: 'Continue Shopping',
    backToStore: 'Back to Store',
    inStockShort: 'In Stock',
    outOfStockShort: 'Out of Stock',
    save: 'Save',
    brandLabel: 'Brand:',
    writeReview: 'Write a Review',
    yourRating: 'Your Rating',
    comment: 'Comment',
    submitReview: 'Submit Review',
    submitting: 'Submitting...',
    loginToReview: 'Please log in to submit a review for this product.',
    reviewSuccess: 'Review added successfully!',
    reviewFailed: 'Failed to submit review. You can only review products you have purchased.',
    reviewError: 'Error submitting review',
    loginSignUp: 'Login / Sign Up',
    relatedProducts: 'Related Products',
    customerReviewsTitle: 'Customer Reviews',
    recentReviews: 'Recent Reviews',
    noReviews: 'No reviews yet for this product. Be the first to buy and write a review!',
    productVideo: 'Product Video Demonstration',
    // Additional checkout / details / reels keys
    productNotFound: 'Product not found.',
    backToShop: 'Back to Shop',
    reviewsCount: '({count} reviews)',
    saveDiscount: 'Save {percent}%',
    placeholderReview: 'What did you think of this product? Write your honest review here...',
    invalidVideoUrl: 'Invalid video URL.',
    reviewsSub: 'What our buyers say about this product.',
    free: 'FREE',
    placeholderName: 'e.g. John Doe',
    placeholderAddress: 'Street address, building, floor etc.',
    placeholderCity: 'e.g. Dhaka',
    placeholderPostalCode: 'e.g. 1212',
    placeholderPhone: 'e.g. +8801712345678',
    otpRequiredWarning: '* Please verify your phone number using OTP to proceed.',
    verifyPhoneAlert: 'Please verify your phone number using OTP first.',
    otpSentSuccess: 'OTP sent to your phone!',
    otpSendFailed: 'Failed to send OTP',
    enterValidPhone: 'Please enter a valid phone number',
    enterOtpCode: 'Please enter the OTP code',
    phoneVerifiedSuccess: 'Phone number verified!',
    invalidOtpCode: 'Invalid OTP code',
    orderPlaceError: 'Error placing order',
    couponAppliedSuccess: 'Coupon applied! {discount}% discount.',
    couponApplyFailed: 'Failed to apply coupon',
    cashOnDelivery: 'Cash on Delivery',
    payCashOnDelivery: 'Pay cash upon physical delivery',
    instantMobilePayment: 'Pay instantly using your bKash wallet',
    fastMobileBanking: 'Fast and secure mobile banking with Nagad',
    gatewayMethods: 'Cards, Net Banking, and other mobile wallets',
    orderPlacedNote: 'Your order #{orderId} has been successfully placed. We will contact you shortly to confirm.',
    advancePaymentPolicy: 'Orders above {threshold} require a {percent}% advance payment to prevent spam/fake orders.',
    requiredAdvanceAmount: 'Required Advance Amount',
    remainingOnDelivery: 'Remaining {remaining} can be paid Cash on Delivery.',
    loadingVideos: 'Loading videos...',
    noVideosAvailable: 'No Videos Available',
    noVideosNote: 'There are no shoppable reels added by admin yet. Check back later!',
    backToHome: 'Back to Home',
    comments: 'Comments',
    noComments: 'No comments yet. Write yours below!',
    writeCommentPlaceholder: 'Write a comment...',
    linkCopied: 'Link copied to clipboard!',
    // Admin
    visitStore: 'Visit Store',
    clearCache: 'Clear Cache',
    printPage: 'Print Page',
    notifications: 'Notifications',
    language: 'Language',
  },
  bn: {
    // Header top bar
    findStore: 'স্টোর খুঁজুন',
    compare: 'তুলনা করুন',
    compareTitle: 'পণ্য তুলনা করুন',
    comparePriceDiff: 'সাশ্রয়',
    regularPrice: 'সাধারণ মূল্য',
    discountPrice: 'ছাড়ের মূল্য',
    emptyCompare: 'আপনার তুলনা তালিকা খালি!',
    addToCompare: 'তুলনা তালিকায় যোগ করুন',
    maxCompareLimit: 'সর্বোচ্চ ৩টি পণ্য তুলনা করা যাবে',
    trackOrder: 'অর্ডার ট্র্যাক',
    helpline: 'হেল্পলাইন',
    // Nav
    home: 'হোম',
    shop: 'শপ',
    categories: 'ক্যাটাগরি',
    dashboard: 'ড্যাশবোর্ড',
    adminPanel: 'অ্যাডমিন প্যানেল',
    brands: 'ব্র্যান্ড',
    dailyDeals: 'ডেইলি ডিলস',
    pages: 'পেইজ',
    shopByCategories: 'ক্যাটাগরি দিয়ে কিনুন',
    products: 'পণ্য',
    store: 'স্টোর',
    // Auth
    login: 'লগইন',
    logout: 'লগআউট',
    // Cart
    addToCart: 'কার্টে যোগ করুন',
    add: 'যোগ করুন',
    quickView: 'দ্রুত দেখুন',
    buyNow: 'এখনই কিনুন',
    whatsappOrder: 'হোয়াটসঅ্যাপে অর্ডার',
    callToOrder: 'ফোনে অর্ডার',
    viewFullDetails: 'বিস্তারিত দেখুন',
    featuredProducts: 'বিশেষ পণ্য',
    handpicked: 'আপনার জন্য বাছাই করা সেরা কালেকশন।',
    viewAll: 'সব দেখুন',
    inStock: 'স্টকে আছে',
    outOfStock: 'স্টক নেই',
    quantity: 'পরিমাণ',
    freeDelivery: 'বিনামূল্যে ডেলিভারি',
    freeDeliveryNote: '৳১০০ এর উপরে অর্ডারে',
    returnPolicy: '৩০ দিন রিটার্ন',
    returnNote: 'মানি ব্যাক গ্যারান্টি',
    secureCheckout: 'নিরাপদ চেকআউট',
    secureNote: '১০০% নিরাপদ পেমেন্ট',
    customerReviews: 'গ্রাহক রিভিউ',
    // Wishlist
    wishlist: 'উইশলিস্ট',
    yourWishlist: 'আপনার উইশলিস্ট',
    wishlistEmpty: 'আপনার উইশলিস্ট খালি। পছন্দের পণ্যে হার্ট আইকনে ক্লিক করুন!',
    // Shop
    allProducts: 'সকল পণ্য',
    showing: 'দেখানো হচ্ছে',
    results: 'টি ফলাফল',
    allCategories: 'সকল ক্যাটাগরি',
    allBrands: 'সকল ব্র্যান্ড',
    allRatings: 'সকল রেটিং',
    above: 'এবং উপরে',
    filters: 'ফিল্টার',
    reset: 'রিসেট',
    price: 'মূল্য',
    rating: 'রেটিং',
    brand: 'ব্র্যান্ড',
    newest: 'নতুন',
    oldest: 'পুরনো',
    priceLowHigh: 'মূল্য: কম → বেশি',
    priceHighLow: 'মূল্য: বেশি → কম',
    loadMore: 'আরও পণ্য লোড করুন',
    loading: 'লোড হচ্ছে...',
    noProducts: 'আপনার ফিল্টারে কোনো পণ্য পাওয়া যায়নি।',
    resetFilters: 'ফিল্টার রিসেট করুন',
    // Checkout
    secureCheckoutTitle: 'নিরাপদ চেকআউট',
    encryptedCheckout: '১০০% এনক্রিপ্টেড চেকআউট অভিজ্ঞতা।',
    myCart: 'আমার কার্ট',
    shipping: 'শিপিং',
    payment: 'পেমেন্ট',
    success: 'সফল',
    cartEmpty: 'আপনার কার্ট খালি',
    cartEmptyNote: 'আপনি এখনো কোনো পণ্য কার্টে যোগ করেননি। কেনাকাটা শুরু করতে আমাদের কালেকশন দেখুন!',
    startShopping: 'কেনাকাটা শুরু করুন',
    productDetails: 'পণ্যের বিবরণ',
    items: 'টি পণ্য',
    orderSummary: 'অর্ডার সারসংক্ষেপ',
    haveCoupon: 'কুপন কোড আছে?',
    selectCode: 'কোড বেছে নিন...',
    applied: 'প্রয়োগ হয়েছে',
    apply: 'প্রয়োগ করুন',
    remove: 'সরান',
    coupon: 'কুপন',
    subtotal: 'সাবটোটাল',
    shippingCost: 'শিপিং',
    couponDiscount: 'কুপন ছাড়',
    totalPrice: 'মোট মূল্য',
    checkout: 'চেকআউট করুন',
    shippingAddress: 'শিপিং ঠিকানা',
    shippingAddressNote: 'আপনার ডেলিভারি ঠিকানার বিবরণ দিন।',
    fullName: 'পূর্ণ নাম',
    deliveryAddress: 'ডেলিভারি ঠিকানা',
    city: 'শহর',
    postalCode: 'পোস্টাল কোড',
    phoneVerification: 'ফোন যাচাইকরণ (OTP প্রয়োজন)',
    sendOtp: 'OTP পাঠান',
    sending: 'পাঠানো হচ্ছে...',
    verify: 'যাচাই করুন',
    verifying: 'যাচাই হচ্ছে...',
    verified: 'যাচাই হয়েছে!',
    enterOtp: '৬ সংখ্যার OTP কোড লিখুন',
    otpWarning: '* অনুগ্রহ করে OTP দিয়ে ফোন নম্বর যাচাই করুন।',
    shippingMethods: 'ডেলিভারি পদ্ধতি',
    shippingMethodNote: 'আপনার পছন্দের ডেলিভারি পদ্ধতি বেছে নিন।',
    confirmationSummary: 'নিশ্চিতকরণ সারসংক্ষেপ',
    itemsSubtotal: 'পণ্যের সাবটোটাল',
    deliveryShipping: 'ডেলিভারি শিপিং',
    grandTotal: 'সর্বমোট',
    backToCart: 'কার্টে ফিরুন',
    nextPayment: 'পরবর্তী: পেমেন্ট',
    advancePaymentRequired: 'অগ্রিম পেমেন্ট প্রয়োজন',
    paymentOptions: 'পেমেন্ট পদ্ধতি',
    paymentOptionsNote: 'নিরাপদ তালিকা থেকে আপনার পছন্দের পেমেন্ট পদ্ধতি বেছে নিন।',
    finalCheckout: 'চূড়ান্ত চেকআউট',
    shippingDelivery: 'শিপিং ডেলিভারি',
    discountApplied: 'ছাড় প্রযোজ্য',
    totalPayable: 'মোট পরিশোধযোগ্য',
    back: 'পেছনে',
    placingOrder: 'অর্ডার দেওয়া হচ্ছে...',
    confirmOrder: 'অর্ডার নিশ্চিত করুন',
    thankYou: 'আপনার অর্ডারের জন্য ধন্যবাদ!',
    orderPlaced: 'সফলভাবে অর্ডার দেওয়া হয়েছে।',
    orderStatus: 'অর্ডার স্ট্যাটাস:',
    pendingConfirmation: 'নিশ্চিতকরণ পেন্ডিং',
    paymentSelection: 'পেমেন্ট পদ্ধতি:',
    deliveryMethod: 'ডেলিভারি পদ্ধতি:',
    totalBill: 'মোট বিল:',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    backToStore: 'স্টোরে ফিরুন',
    inStockShort: 'স্টকে আছে',
    outOfStockShort: 'স্টক নেই',
    save: 'সেভ',
    brandLabel: 'ব্র্যান্ড:',
    writeReview: 'রিভিউ লিখুন',
    yourRating: 'আপনার রেটিং',
    comment: 'মন্তব্য',
    submitReview: 'রিভিউ জমা দিন',
    submitting: 'জমা হচ্ছে...',
    loginToReview: 'রিভিউ দিতে প্রথমে লগইন করুন।',
    reviewSuccess: 'রিভিউ সফলভাবে যুক্ত হয়েছে!',
    reviewFailed: 'রিভিউ জমা দিতে ব্যর্থ হয়েছে। আপনি কেবল আপনার কেনা পণ্যের রিভিউ দিতে পারবেন।',
    reviewError: 'রিভিউ জমা দিতে সমস্যা হয়েছে',
    loginSignUp: 'লগইন / সাইন আপ',
    relatedProducts: 'সম্পর্কিত পণ্য',
    customerReviewsTitle: 'গ্রাহক রিভিউ',
    recentReviews: 'সাম্প্রতিক রিভিউ',
    noReviews: 'এখনো কোনো রিভিউ নেই। প্রথম ক্রেতা হিসেবে রিভিউ লিখুন!',
    productVideo: 'পণ্যের ভিডিও প্রদর্শনী',
    // Additional checkout / details / reels keys
    productNotFound: 'পণ্যটি পাওয়া যায়নি।',
    backToShop: 'শপে ফিরুন',
    reviewsCount: '({count} টি রিভিউ)',
    saveDiscount: '{percent}% ছাড়',
    placeholderReview: 'এই পণ্যটি সম্পর্কে আপনার মতামত কী? আপনার রিভিউটি এখানে লিখুন...',
    invalidVideoUrl: 'অকার্যকর ভিডিও ইউআরএল।',
    reviewsSub: 'এই পণ্যটি সম্পর্কে ক্রেতাদের মতামত।',
    free: 'ফ্রি',
    placeholderName: 'যেমন: জন ডো',
    placeholderAddress: 'রাস্তার ঠিকানা, ভবন, ফ্ল্যাট ইত্যাদি',
    placeholderCity: 'যেমন: ঢাকা',
    placeholderPostalCode: 'যেমন: ১২১২',
    placeholderPhone: 'যেমন: +৮৮০১৭১২৩৪৫৬৭৮',
    otpRequiredWarning: '* অনুগ্রহ করে ওটিপি (OTP) দিয়ে আপনার ফোন নম্বরটি যাচাই করুন।',
    verifyPhoneAlert: 'অনুগ্রহ করে প্রথমে ওটিপি (OTP) দিয়ে আপনার ফোন নম্বরটি যাচাই করুন।',
    otpSentSuccess: 'আপনার ফোনে ওটিপি পাঠানো হয়েছে!',
    otpSendFailed: 'ওটিপি পাঠাতে ব্যর্থ হয়েছে',
    enterValidPhone: 'অনুগ্রহ করে একটি সঠিক ফোন নম্বর লিখুন',
    enterOtpCode: 'অনুগ্রহ করে ওটিপি কোডটি লিখুন',
    phoneVerifiedSuccess: 'ফোন নম্বর সফলভাবে যাচাই হয়েছে!',
    invalidOtpCode: 'অকার্যকর ওটিপি কোড',
    orderPlaceError: 'অর্ডার দিতে সমস্যা হয়েছে',
    couponAppliedSuccess: 'কুপন সফলভাবে প্রয়োগ করা হয়েছে! {discount}% ছাড়।',
    couponApplyFailed: 'কুপন প্রয়োগ করতে ব্যর্থ হয়েছে',
    cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
    payCashOnDelivery: 'পণ্য হাতে পেয়ে মূল্য পরিশোধ করুন',
    instantMobilePayment: 'বিকাশ ওয়ালেট ব্যবহার করে ইনস্ট্যান্ট পেমেন্ট করুন',
    fastMobileBanking: 'নগদ মোবাইল ব্যাংকিংয়ের মাধ্যমে দ্রুত ও নিরাপদ পেমেন্ট',
    gatewayMethods: 'কার্ড, নেট ব্যাংকিং এবং অন্যান্য মোবাইল ওয়ালেট',
    orderPlacedNote: 'আপনার অর্ডারটি #{orderId} সফলভাবে সম্পন্ন হয়েছে। নিশ্চিতকরণের জন্য শীঘ্রই আপনার সাথে যোগাযোগ করা হবে।',
    advancePaymentPolicy: 'স্প্যাম/ফেইক অর্ডার রোধ করতে {threshold} টাকার বেশি অর্ডারে {percent}% অগ্রিম পেমেন্ট প্রয়োজন।',
    requiredAdvanceAmount: 'প্রয়োজনীয় অগ্রিম টাকা',
    remainingOnDelivery: 'বাকি {remaining} টাকা ডেলিভারির সময় ক্যাশ অন ডেলিভারিতে দেওয়া যাবে।',
    loadingVideos: 'ভিডিও লোড হচ্ছে...',
    noVideosAvailable: 'কোনো ভিডিও নেই',
    noVideosNote: 'অ্যাডমিন এখনো কোনো শপ-যোগ্য রিল যুক্ত করেননি। পরে আবার চেক করুন!',
    backToHome: 'হোমে ফিরুন',
    comments: 'মন্তব্য সমূহ',
    noComments: 'এখনো কোনো মন্তব্য নেই। নিচে আপনার মন্তব্য লিখুন!',
    writeCommentPlaceholder: 'একটি মন্তব্য লিখুন...',
    linkCopied: 'লিঙ্ক ক্লিপবোর্ডে কপি করা হয়েছে!',
    // Admin
    visitStore: 'স্টোর দেখুন',
    clearCache: 'ক্যাশ মুছুন',
    printPage: 'প্রিন্ট করুন',
    notifications: 'নোটিফিকেশন',
    language: 'ভাষা',
  }
};

export const LanguageContext = createContext({
  lang: 'en',
  t: (key) => key,
  setLang: () => {},
  isBn: false,
});

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('en');

  useEffect(() => {
    const stored = localStorage.getItem('goroly-lang');
    if (stored === 'bn' || stored === 'en') {
      setLangState(stored);
      document.documentElement.setAttribute('lang', stored === 'bn' ? 'bn' : 'en');
    }
  }, []);

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('goroly-lang', newLang);
    document.documentElement.setAttribute('lang', newLang === 'bn' ? 'bn' : 'en');
  };

  const t = (key, replacements) => {
    let text = translations[lang]?.[key] || translations['en']?.[key] || key;
    if (replacements && typeof replacements === 'object') {
      Object.entries(replacements).forEach(([k, v]) => {
        text = text.replace(new RegExp(`{${k}}`, 'g'), v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, t, setLang, isBn: lang === 'bn' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
