ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS header_bg_color TEXT DEFAULT '#F97316',
  ADD COLUMN IF NOT EXISTS header_text_color TEXT DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS header_accent_color TEXT DEFAULT '#FF6600';
